[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "RoKi-central.hex",
]
dependencies = ["build"]

[tasks.objcopy-left]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "left",
    "--",
    "-O",
    "ihex",
    "RoKi-left.hex",
]
dependencies = ["build"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "RoKi-central.hex",
    "--output-path",
    "RoKi-central.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-central"]

[tasks.uf2-left]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "RoKi-left.hex",
    "--output-path",
    "RoKi-left.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-left"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-left", "uf2-right", "uf2-trackball"]

[tasks.objcopy-right]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--help",
] }
command = "cargo"
args = [
  "objcopy",
  "--release",
  "--bin",
  "right",
  "--",
  "-O",
  "ihex",
  "RoKi-right.hex",
]
dependencies = ["build"]

[tasks.uf2-right]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
  "hex-to-uf2",
  "--help",
] }
command = "cargo"
args = [
  "hex-to-uf2",
  "--input-path",
  "RoKi-right.hex",
  "--output-path",
  "RoKi-right.uf2",
  "--family",
  "nrf52840",
]
dependencies = ["objcopy-right"]

[tasks.objcopy-trackball]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
  "objcopy",
  "--help",
] }
command = "cargo"
args = [
  "objcopy",
  "--release",
  "--bin",
  "trackball",
  "--",
  "-O",
  "ihex",
  "RoKi-trackball.hex",
]
dependencies = ["build"]

[tasks.uf2-trackball]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
  "hex-to-uf2",
  "--help",
] }
command = "cargo"
args = [
  "hex-to-uf2",
  "--input-path",
  "RoKi-trackball.hex",
  "--output-path",
  "RoKi-trackball.uf2",
  "--family",
  "nrf52840",
]
dependencies = ["objcopy-trackball"]
